// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjoituvqpmocpudcbwlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb2l0dXZxcG1vY3B1ZGNid2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDU1MDIsImV4cCI6MjA3MDk4MTUwMn0.j1UThuFAwXMoc4TxnQ52MhGx1XaEFf9IhVQ93BdiVRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});